package com.designPatterns.safedec.Views;

import com.designPatterns.safedec.business.ActiveSystemState;
import com.designPatterns.safedec.business.BuildingSystem;
import com.designPatterns.safedec.business.SystemState;
import com.designPatterns.safedec.models.Sensor;
import com.designPatterns.safedec.models.Alarm;
import com.designPatterns.safedec.models.MotionSensor;
import com.designPatterns.safedec.service.DashBoardService;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author akshayharyani
 */
public class DashboardPanel extends javax.swing.JPanel {

    /**
     * Creates new form DashboardPanel
     */
    private SystemState systemState;
    private BuildingSystem buildingSystem;
    private Boolean systemActive = true;
    
    public DashboardPanel() {
        initComponents();
        updateComponents();
        systemState = new ActiveSystemState();
        buildingSystem = new BuildingSystem(systemState);
        
    }
    
        private void updateComponents(){
        DashBoardService dashBoardService = new DashBoardService();
        List<Sensor> allSensors = dashBoardService.getAllSensors();
        List< Alarm > allAlarms = dashBoardService.getAllAlarmSensors();
        javax.swing.table.DefaultTableModel sensorModel = (javax.swing.table.DefaultTableModel) SensorsTable.getModel();
        
        for( Sensor sensor : allSensors )
        {
            String type = "fire sensor";
            if (sensor instanceof MotionSensor){
                type = "motion sensor ";
                MotionSensor ms = (MotionSensor) sensor;
                if(ms.isIsCamera())
                    type += "(with camera)";
                else
                    type += "(without camera)";

            }
                    
            Object[]  tableRow = new Object[8];
            tableRow[0]= sensor.getId();
            tableRow[1]= sensor.getSectionId();
            tableRow[2]= type;
            tableRow[3]= sensor.getPrice();
            tableRow[4]= sensor.getLoc().getX1()+","+sensor.getLoc().getY1();
            
             sensorModel.addRow(tableRow);
        }
        
        javax.swing.table.DefaultTableModel alarmModel = (javax.swing.table.DefaultTableModel) AlarmTable.getModel();
         for( Alarm alarm : allAlarms )
         {
            Object[]  tableRow = new Object[8];
            tableRow[0]= alarm.getAlarmId();
            tableRow[1]= alarm.getSensorId();
            tableRow[2]= alarm.getOccuranceDate();
            tableRow[3]= alarm.getMemo();
             alarmModel.addRow(tableRow);
             
         }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        statusLabel = new javax.swing.JLabel();
        statusCodeLabel = new javax.swing.JLabel();
        statusToggleButton = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        SensorsTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        AlarmTable = new javax.swing.JTable();

        statusLabel.setText("Status");

        statusCodeLabel.setText("Active");

        statusToggleButton.setText("Deactivate");
        statusToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusToggleButtonActionPerformed(evt);
            }
        });

        SensorsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{

            },
            new String [] {
                "Sensor Id", "Section Id", "Sensor Type", "Sensor Cost", "Sensor Position"
            }
        ));
        SensorsTable.setSize(new java.awt.Dimension(1500, 1500));
        jScrollPane1.setViewportView(SensorsTable);

        jLabel1.setText("Sensors");

        jLabel4.setText("Alarms");

        AlarmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][]{

            },
            new String [] {
                "Alarm Id", "Related Sensor Id", "Occurance date", "Memo"
            }
        ));
        jScrollPane2.setViewportView(AlarmTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(statusLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(statusCodeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                                .addComponent(statusToggleButton)))
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLabel)
                    .addComponent(statusCodeLabel)
                    .addComponent(statusToggleButton))
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void statusToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusToggleButtonActionPerformed
        // TODO add your handling code here:
        systemActive = !systemActive;
        if(systemActive){
            statusCodeLabel.setText("Active");
            statusToggleButton.setText("Deactivate");
            
        }else{
            statusCodeLabel.setText("Inactive");
            statusToggleButton.setText("Activate");
        }
        buildingSystem.nextState();
    }//GEN-LAST:event_statusToggleButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AlarmTable;
    private javax.swing.JTable SensorsTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel statusCodeLabel;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JToggleButton statusToggleButton;
    // End of variables declaration//GEN-END:variables
}
