/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.designPatterns.safedec.Views;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author akshayharyani
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        JPanel dashboardPanel = new DashboardPanel();
        jPanel3.removeAll();
        jPanel3.add(dashboardPanel);
        jPanel3.revalidate();
        jPanel3.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        dashboardMenuPanel = new javax.swing.JPanel();
        javax.swing.JLabel dashboardMenuLabel = new javax.swing.JLabel();
        productMenuPanel = new javax.swing.JPanel();
        controlPanelMenuLabel = new javax.swing.JLabel();
        profileMenuPanel = new javax.swing.JPanel();
        profileMenuLabel = new javax.swing.JLabel();
        billingMenuPanel = new javax.swing.JPanel();
        billingMenuLabel = new javax.swing.JLabel();
        accountsMenuPanel = new javax.swing.JPanel();
        scheduleMenuLabel = new javax.swing.JLabel();
        reportsMenuPanel = new javax.swing.JPanel();
        aboutMenuLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(67, 104, 145));
        jPanel1.setToolTipText("");

        jPanel5.setBackground(new java.awt.Color(67, 104, 145));
        jPanel5.setLayout(new java.awt.GridLayout(0, 1, 0, 5));

        dashboardMenuPanel.setBackground(new java.awt.Color(0, 128, 145));
        dashboardMenuPanel.setPreferredSize(new java.awt.Dimension(300, 40));


        dashboardMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dashboardMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        dashboardMenuLabel.setText("DASHBOARD");
        dashboardMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout dashboardMenuPanelLayout = new javax.swing.GroupLayout(dashboardMenuPanel);
        dashboardMenuPanel.setLayout(dashboardMenuPanelLayout);
        dashboardMenuPanelLayout.setHorizontalGroup(
            dashboardMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashboardMenuPanelLayout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(dashboardMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dashboardMenuPanelLayout.setVerticalGroup(
            dashboardMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dashboardMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(dashboardMenuPanel);

        productMenuPanel.setBackground(new java.awt.Color(0, 128, 145));
        productMenuPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        controlPanelMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        controlPanelMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        controlPanelMenuLabel.setText("CONTROL PANEL");
        controlPanelMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                controlPanelMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout productMenuPanelLayout = new javax.swing.GroupLayout(productMenuPanel);
        productMenuPanel.setLayout(productMenuPanelLayout);
        productMenuPanelLayout.setHorizontalGroup(
            productMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productMenuPanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(controlPanelMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        productMenuPanelLayout.setVerticalGroup(
            productMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(controlPanelMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(productMenuPanel);

        profileMenuPanel.setBackground(new java.awt.Color(0, 128, 145));
        profileMenuPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        profileMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        profileMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileMenuLabel.setText("PROFILE");
        profileMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout profileMenuPanelLayout = new javax.swing.GroupLayout(profileMenuPanel);
        profileMenuPanel.setLayout(profileMenuPanelLayout);
        profileMenuPanelLayout.setHorizontalGroup(
            profileMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profileMenuPanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(profileMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        profileMenuPanelLayout.setVerticalGroup(
            profileMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profileMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(profileMenuPanel);

        billingMenuPanel.setBackground(new java.awt.Color(0, 128, 145));
        billingMenuPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        billingMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        billingMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        billingMenuLabel.setText("BILLING");
        billingMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billingMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout billingMenuPanelLayout = new javax.swing.GroupLayout(billingMenuPanel);
        billingMenuPanel.setLayout(billingMenuPanelLayout);
        billingMenuPanelLayout.setHorizontalGroup(
            billingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, billingMenuPanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(billingMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        billingMenuPanelLayout.setVerticalGroup(
            billingMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(billingMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(billingMenuPanel);

        accountsMenuPanel.setBackground(new java.awt.Color(0, 128, 145));
        accountsMenuPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        scheduleMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        scheduleMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        scheduleMenuLabel.setText("SCHEDULE");
        scheduleMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scheduleMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout accountsMenuPanelLayout = new javax.swing.GroupLayout(accountsMenuPanel);
        accountsMenuPanel.setLayout(accountsMenuPanelLayout);
        accountsMenuPanelLayout.setHorizontalGroup(
            accountsMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountsMenuPanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(scheduleMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        accountsMenuPanelLayout.setVerticalGroup(
            accountsMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scheduleMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(accountsMenuPanel);

        reportsMenuPanel.setBackground(new java.awt.Color(0, 128, 145));
        reportsMenuPanel.setPreferredSize(new java.awt.Dimension(300, 40));

        aboutMenuLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        aboutMenuLabel.setForeground(new java.awt.Color(255, 255, 255));
        aboutMenuLabel.setText("ABOUT");
        aboutMenuLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutMenuLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout reportsMenuPanelLayout = new javax.swing.GroupLayout(reportsMenuPanel);
        reportsMenuPanel.setLayout(reportsMenuPanelLayout);
        reportsMenuPanelLayout.setHorizontalGroup(
            reportsMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, reportsMenuPanelLayout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addComponent(aboutMenuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        reportsMenuPanelLayout.setVerticalGroup(
            reportsMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(aboutMenuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel5.add(reportsMenuPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(67, 104, 145));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Safe Dec");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(728, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void profileMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMenuLabelMouseClicked
        // TODO add your handling code here:
        JPanel profilePanel = new ProfilePanel();
                jPanel3.removeAll();
        jPanel3.add(profilePanel);
        jPanel3.revalidate();
        jPanel3.repaint();

    }//GEN-LAST:event_profileMenuLabelMouseClicked

    private void billingMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billingMenuLabelMouseClicked
        // TODO add your handling code here:
        JPanel billingPanel = new BillingPanel();
        jPanel3.removeAll();
        jPanel3.add(billingPanel);
        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_billingMenuLabelMouseClicked

    private void dashboardMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardMenuLabelMouseClicked
        // TODO add your handling code here:
        JPanel dashboardPanel = new DashboardPanel();
        jPanel3.removeAll();
        jPanel3.add(dashboardPanel);
        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_dashboardMenuLabelMouseClicked

    private void controlPanelMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_controlPanelMenuLabelMouseClicked
        // TODO add your handling code here:
        JPanel controlPanel = new MapPanel();
        jPanel3.removeAll();
        jPanel3.add(controlPanel);
        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_controlPanelMenuLabelMouseClicked

    private void scheduleMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scheduleMenuLabelMouseClicked
        // TODO add your handling code here:
        JPanel schedulePanel = new SchedulePanel();
        jPanel3.removeAll();
        jPanel3.add(schedulePanel);
        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_scheduleMenuLabelMouseClicked

    private void aboutMenuLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutMenuLabelMouseClicked
        // TODO add your handling code here:
        JPanel aboutPanel = new AboutPanel();
        jPanel3.removeAll();
        jPanel3.add(aboutPanel);
        jPanel3.revalidate();
        jPanel3.repaint();
    }//GEN-LAST:event_aboutMenuLabelMouseClicked



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutMenuLabel;
    private javax.swing.JPanel accountsMenuPanel;
    private javax.swing.JLabel billingMenuLabel;
    private javax.swing.JPanel billingMenuPanel;
    private javax.swing.JLabel controlPanelMenuLabel;
    private javax.swing.JPanel dashboardMenuPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel productMenuPanel;
    private javax.swing.JLabel profileMenuLabel;
    private javax.swing.JPanel profileMenuPanel;
    private javax.swing.JPanel reportsMenuPanel;
    private javax.swing.JLabel scheduleMenuLabel;
    // End of variables declaration//GEN-END:variables
  }
