/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.designPatterns.safedec.Views;

import com.designPatterns.safedec.controls.ViewController;
import com.designPatterns.safedec.models.Customer;
import com.designPatterns.safedec.models.CustomerBuilder;
import com.designPatterns.safedec.service.UserAdminService;
import com.designPatterns.safedec.service.UserAdminServiceImpl;
import javax.swing.JOptionPane;

/**
 *
 * @author akshayharyani
 */
public class ProfilePanel extends javax.swing.JPanel {

    Customer currentUser;
    
    /**
     * Creates new form ProfilePanel
     */
    public ProfilePanel() {
        initComponents();
        fillUserData();

    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ServiceIdLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        ServiceIdField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        FirstNameField = new javax.swing.JTextField();
        AddressField = new javax.swing.JTextField();
        EmailField = new javax.swing.JTextField();
        PhoneField = new javax.swing.JTextField();
        EmergencyContact1Field = new javax.swing.JTextField();
        EmergencyContact2Field = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(500, 500));

        ServiceIdLabel.setText("Service Id");
        ServiceIdLabel.setToolTipText("");

        FirstNameLabel.setText("Name");
        FirstNameLabel.setToolTipText("");

        ServiceIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ServiceIdFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Address");

        jLabel2.setText("Email");

        jLabel3.setText("Phone");

        jLabel5.setText("Emergency Contact 1");

        jLabel6.setText("Emergency Contact 2");

        saveButton.setText("save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        FirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameFieldActionPerformed(evt);
            }
        });

        AddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressFieldActionPerformed(evt);
            }
        });

        EmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailFieldActionPerformed(evt);
            }
        });

        PhoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhoneFieldActionPerformed(evt);
            }
        });

        EmergencyContact1Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyContact1FieldActionPerformed(evt);
            }
        });

        EmergencyContact2Field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmergencyContact2FieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(FirstNameLabel)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(ServiceIdLabel)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmergencyContact1Field, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(ServiceIdField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FirstNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(AddressField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EmailField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PhoneField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EmergencyContact2Field, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ServiceIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ServiceIdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(AddressField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(PhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmergencyContact1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmergencyContact2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(saveButton)
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ServiceIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServiceIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ServiceIdFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        
        UserAdminService userAdminService = new UserAdminServiceImpl();
        int customerId = Integer.valueOf(ServiceIdField.getText());
        String customerName = FirstNameField.getText();
        String propertyAddress = AddressField.getText();
        String phoneNumber = PhoneField.getText();
        String emailAddress = EmailField.getText();
        String primaryContactNumber = EmergencyContact1Field.getText();
        String secondaryContactNumber = EmergencyContact2Field.getText();
        
        Customer updatedCustomerInfo= new CustomerBuilder().setCustomerName(customerName).setPropertyAddress(propertyAddress).setPhoneNumber(phoneNumber).setEmaiAddress(emailAddress).setPrimaryContactNumber(primaryContactNumber).setSecondaryContactNumber(secondaryContactNumber).setLicenseCode(currentUser.getLicenseCode()).setMasterPassword(currentUser.getMasterPassword()).setCustomerId(customerId).build();
       // newCustomerInfo.setCustomerId(customerId);
        
        if (userAdminService.editUser(updatedCustomerInfo)) {
            JOptionPane.showMessageDialog(null, "Successfully updated account details");
        } else {
            JOptionPane.showMessageDialog(null, "Failed to  update account details");
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    private void FirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameFieldActionPerformed

    private void AddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFieldActionPerformed

    private void EmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailFieldActionPerformed

    private void PhoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhoneFieldActionPerformed

    private void EmergencyContact1FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyContact1FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmergencyContact1FieldActionPerformed

    private void EmergencyContact2FieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmergencyContact2FieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmergencyContact2FieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressField;
    private javax.swing.JTextField EmailField;
    private javax.swing.JTextField EmergencyContact1Field;
    private javax.swing.JTextField EmergencyContact2Field;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField PhoneField;
    private javax.swing.JTextField ServiceIdField;
    private javax.swing.JLabel ServiceIdLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables

    private void fillUserData() {
        currentUser = ViewController.getInstance().getLoggedInUser();
        ServiceIdField.setText(String.valueOf(currentUser.getCustomerId()));
        FirstNameField.setText(currentUser.getCustomerName());
        AddressField.setText(currentUser.getPropertyAddress());
        EmailField.setText(currentUser.getEmailAddress());
        PhoneField.setText(currentUser.getPhoneNumber());
        EmergencyContact1Field.setText(currentUser.getPrimaryContactNumber());        
        EmergencyContact2Field.setText(currentUser.getSecondaryContactNumber());
        
        validate();
        repaint();
    }
}
